language: node_js
node_js:
  - 14
install:
  - npm install -g codecov
script:
  - cd client ; npm install
  - npm test
  - cd ..
  - cd server ; npm install
  - npm test
  - cd ..
  - codecov
  - cd server
  - npm start & PIDS="$!"
  - cd ../client
  - npm run start-test & PIDS="$!"
  - sleep 30
  - npx cypress run
  - npx nyc report --reporter=lcov
  - codecov