language: node_js
node_js:
  - 14
install:
  - npm install -g codecov
script:
  - cd client ; npm install
  - npm test
  - cd ..
  - cd server ; npm install
  - npm test
  - cd ..
  - codecov
  - cd server
  - npm run start:ci&
  - sleep 30
  - cd ../client
  - npm run ci:client"
  - npx nyc report --reporter=lcov
  - codecov